- platform: template
  sensors:
    vw_passat_b8_tankvolumen:
      friendly_name: "Tankgröße"
      unique_id: "vw_passat_b8_tankgroesse"
      device_class: volume
      unit_of_measurement: L
      value_template: >
          {% if is_state('sensor.vw_passat_b8_tankgroesse', 'Unknown') %}
           {{ Unbekannt }}
          {% else %}
           {{ Unbekannt }}
          {% endif %}
      icon_template: >-
        {% if is_state('sensor.vw_passat_b8_tankgroesse', 'Unknown') %}
          mdi:gas-station-outline
        {% else %}
          mdi:gas-station
        {% endif %}
    vw_passat_b8_nachfuellbarer_tank:
      friendly_name: "Nachfüllbarer Tank"
      unique_id: "vw_passat_b8_nachfuellbarer_tank"
      device_class: volume
      unit_of_measurement: L
      value_template: >
          {% if is_state('sensor.vw_passat_b8_nachfuellbarer_tank', 'Unknown')                                                                                                                                                              %}
           {{ Unbekannt }}
          {% else %}
           {{ Unbekannt }}
          {% endif %}
      icon_template: >-
        {% if is_state('sensor.vw_passat_b8_nachfuellbarer_tank', 'Unknown') %                                                                                                                                                             }
          mdi:gas-station-outline
        {% else %}
          mdi:gas-station
        {% endif %}
    vw_passat_b8_befuellter_tank:
      friendly_name: "Befüllter Tank"
      unique_id: "vw_passat_b8_befuellter_tank"
      device_class: volume
      unit_of_measurement: L
      value_template: >
          {% if is_state('sensor.vw_passat_b8_befuellter_tank', 'Unknown') %}
           {{ Unbekannt }}
          {% else %}
           {{ Unbekannt }}
          {% endif %}
      icon_template: >-
        {% if is_state('sensor.vw_passat_b8_befuellter_tank', 'Unknown') %}
          mdi:gas-station-outline
        {% else %}
          mdi:gas-station
        {% endif %}
